services:
  - type: web
    name: phone-download-service
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase: postgres-db
      - key: ADMIN_TOKEN
        value: "CHANGE_ME_TO_STRONG_TOKEN"
    autoDeploy: true

  - type: postgresql
    name: postgres-db
    plan: free
    region: oregon
    databases:
      - name: default
        user: postgres
        password: ${POSTGRES_PASSWORD}
